Гусева. Task №3
GusevaVarvara/spbu-python-course pull request #2
Opened 2024-10-12 18:53 UTC by GusevaVarvara

**Генераторы векторов RGBA и простых чисел**

- Реализовано генераторное выражение для четырехмерного набора векторов RGBA с четными значениями прозрачности.
- Добавлена функция, возвращающая i-й элемент набора.
- Реализован генератор простых чисел.
- Создан декоратор, возвращающий k-е простое число.
- Написаны тесты для проверки реализованной функциональности.

2024-10-14 15:02 UTC, Krekep requested changes
Необходимы исправления

2024-10-14 15:02 UTC, Krekep commented on .github/workflows/generators_test_checking.yml
> +      - Generators
Я думаю лучше сделать как в `code_style.yml`:
```
on:
  [ push, pull_request ]
```

2024-10-14 15:02 UTC, Krekep commented on project/matrix_operations.py
Зачем Вы хотите его удалить?

2024-10-14 15:02 UTC, Krekep commented on project/vector_operations.py
Зачем Вы хотите его удалить?

2024-10-14 15:02 UTC, Krekep commented on tests/test_matrix_operations.py
Зачем Вы хотите его удалить?

2024-10-14 15:02 UTC, Krekep commented on project/prime_generator.py
> +        n += 2
С одной стороны это решение работает быстрее наивного, но с другой стороны оно требует дополнительной  (и не константой) памяти.
Суть этого генератора в том, что он может сгенерировать бесконечную последовательность простых чисел, но добавив в него массив, в котором хранятся найденный простые, Вы ограничили размер последовательности.
Перепишите его без использования массива с простыми числами

2024-10-14 15:02 UTC, Krekep commented on project/prime_generator.py
> +            generator = func(*args, **kwargs)
Какие аргументы принимает `prime_generator`?

2024-10-14 15:02 UTC, Krekep commented on project/prime_generator.py
> +            return k_element if k_element else "Error: index out of range."
А как можно не найти `k`-е простое число?

2024-10-14 15:02 UTC, Krekep commented on project/rgba_generator.py
> +                    yield r, g, b, a
Формально Вы правы, но перепишите с использованием `if` для демонстрации того, что Вы это умеете

2024-10-14 15:02 UTC, Krekep commented on project/rgba_generator.py
> +                    yield r, g, b, a
Это функция-генератор, а генераторное выражение это что-то в духе
```
(i for i in range(10))
```

2024-10-14 15:02 UTC, Krekep commented on tests/test_prime_generator.py
> +    assert generate_k_prime() == expected
Это не то использование, которое подразумевалось в условии. Декоратор не должен быть одноразовым, он должен возвращать функцию, которая принимает `k` и с помощью генератора простых числе возвращает `k`-е по счёту. К примеру:
```
@some_decorator
def prime_generator():
  # magic here
  
prime_generator(1) -> 2
prime_generator(4) -> 7
prime_generator(5) -> 11
```

2024-10-14 15:02 UTC, Krekep commented on tests/test_rgba_generator.py
> +    assert next(gen) == (0, 0, 1, 0)
Перепишите с использованием `parametrize`

2024-10-14 15:02 UTC, Krekep commented on tests/test_vector_operations.py
Зачем Вы хотите его удалить?

2024-10-15 21:00 UTC, GusevaVarvara commented on .github/workflows/generators_test_checking.yml
> +      - Generators
Хорошо, исправила это в файлах generators_test_checking.yml и generators_type_checking.yml.

2024-10-15 21:12 UTC, GusevaVarvara commented on project/matrix_operations.py
Я сделала merge ветки с прошлым заданием в main. При создании новой ветки для этого задания в ней остались файлы из прошлого задания, и я подумала, что их нужно удалить из этой ветки, чтобы остались только те файлы, которые относятся к текущему заданию.

2024-10-15 21:12 UTC, GusevaVarvara commented on project/vector_operations.py
Я сделала merge ветки с прошлым заданием в main. При создании новой ветки для этого задания в ней остались файлы из прошлого задания, и я подумала, что их нужно удалить из этой ветки, чтобы остались только те файлы, которые относятся к текущему заданию.

2024-10-15 21:12 UTC, GusevaVarvara commented on tests/test_matrix_operations.py
Я сделала merge ветки с прошлым заданием в main. При создании новой ветки для этого задания в ней остались файлы из прошлого задания, и я подумала, что их нужно удалить из этой ветки, чтобы остались только те файлы, которые относятся к текущему заданию.

2024-10-15 21:13 UTC, GusevaVarvara commented on tests/test_vector_operations.py
Я сделала merge ветки с прошлым заданием в main. При создании новой ветки для этого задания в ней остались файлы из прошлого задания, и я подумала, что их нужно удалить из этой ветки, чтобы остались только те файлы, которые относятся к текущему заданию.

2024-10-15 21:22 UTC, GusevaVarvara commented on project/prime_generator.py
> +        n += 2
Исправила, в функции prime_generator убрала использование массива с простыми числами.

2024-10-15 21:26 UTC, GusevaVarvara commented on project/prime_generator.py
> +            generator = func(*args, **kwargs)
Функция prime_generator никаких аргументов не принимает, поэтому не нужно было использовать *args и **kwargs.

2024-10-15 21:30 UTC, GusevaVarvara commented on project/prime_generator.py
> +            return k_element if k_element else "Error: index out of range."
k-е простое число всегда будет найдено, если k - положительное целое число; я убрала лишнюю проверку.

2024-10-15 21:33 UTC, GusevaVarvara commented on project/rgba_generator.py
> +                    yield r, g, b, a
Переписала с использованием if для проверки четности a.

2024-10-15 21:41 UTC, GusevaVarvara commented on project/rgba_generator.py
> +                    yield r, g, b, a
Переписала генератор по-другому, но не использовать функцию вообще у меня не получается, так как просто генераторное выражение, как я понимаю, создает объект-генератор, который нельзя повторно инициализировать, а мне нужно обновлять генератор для работы программы.

2024-10-15 21:57 UTC, GusevaVarvara commented on tests/test_prime_generator.py
> +    assert generate_k_prime() == expected
Исправила реализацию декоратора, чтобы он принимал k и возвращал k-е простое число. Я могу напрямую обернуть prime_generator в декоратор, но тогда, как я понимаю, не получится напрямую (без дополнительных манипуляций) использовать prime_generator как обычный генератор для получения последовательности простых чисел, поэтому я оставила отдельную функцию prime_generator_decorated. Не уверена, какой именно вариант нужно было сделать.

2024-10-15 21:59 UTC, GusevaVarvara commented on tests/test_rgba_generator.py
> +    assert next(gen) == (0, 0, 1, 0)
Переписала тест с использованием @pytest.mark.parametrize.

2024-10-18 18:43 UTC, Krekep approved these changes
Зачтено

2024-10-20 11:30 UTC, merged