Гусева. Task №4.
GusevaVarvara/spbu-python-course pull request #3
Opened 2024-10-21 17:44 UTC by GusevaVarvara

**Пул потоков**

1. Реализован пул потоков:
- Количество потоков задаётся параметром конструктора.
- Задачи добавляются с помощью метода enqueue(task).
- Потоки выполняют задачи или ожидают их, обрабатывая возможные исключения.
- Метод dispose завершает работу потоков, при этом все уже запущенные задачи выполняются до конца.
- Реализована корректная обработка исключений в задачах и завершение выполнения оставшихся задач перед остановкой потоков.

2. Написаны тесты для проверки корректного выполнения задач.

Дополнительно: реализовано параллельное вычисление суммы полного декартового произведения множества целых чисел с использованием concurrent.futures.

2024-10-21 18:46 UTC, Krekep requested changes
В целом всё хорошо, но нет аннотаций типов и документации у функций.
Необходимы исправления

2024-10-21 18:46 UTC, Krekep commented on project/thread_pool.py
> +from queue import Queue, Empty
Этот класс реализует в себе методы для работы с потоками. Из пакетов для работы с многопоточностью по условию задачи разрешён только `threading`

2024-10-21 18:46 UTC, Krekep commented on tests/test_thread_pool.py
> +    assert len(pool.threads) == 3
Почему Вы это не проверяете через `threading.active_count()`?

2024-10-21 18:46 UTC, Krekep commented on tests/test_concurrent_futures.py
> +def test_cartesian_product_sum(numbers, expected_sum):
Попробуйте написать тест, демонстрирующий, что многопроцессорное сложение будет работать быстрее, чем однопоточное

2024-10-22 08:19 UTC, Krekep commented on tests/test_concurrent_futures.py
> +def test_cartesian_product_sum(numbers, expected_sum):
Ладно, скорее всего я был неправ, давая такое задание. Для более тяжёлых функций, чем `sum` задание имело бы смысл, но в с учётом того, что `sum` использует сишную реализацию, оверхед на копирование массивов между процессами и их синхронизацию сильно больше, чем выигрыш от их использования в такой простой задаче. Так что окей, можете не добавлять такой тест. Либо можете добавить более тяжёловесную функцию (добавить, к примеру косинусы, синусы, корни или, к примеру, сортировку сделать) и показать, что с процессами она будет быстрее
Также можете почитать [этот тред](https://www.reddit.com/r/Python/comments/5tfm64/multiprocessing_parallel_sum_slower_than_serial/) и [вот этот](https://stackoverflow.com/questions/42074501/python-concurrent-futures-processpoolexecutor-performance-of-submit-vs-map)

2024-10-22 19:22 UTC, GusevaVarvara commented on project/thread_pool.py
> +from queue import Queue, Empty
Исправила реализацию класса без использования Queue.

2024-10-22 19:33 UTC, GusevaVarvara commented on tests/test_thread_pool.py
> +    assert len(pool.threads) == 3
Я не использовала threading.active_count(), потому что он возвращает общее количество активных потоков в программе и может посчитать другие параллельные потоки, а я хочу проверить их количество только в этом пуле. Я попробовала использовать в этом тесте threading.active_count(), у меня получилось 4 потока, а не 3, как я поняла это из-за того, что при запуске тестов в количестве активных потоков учитывается также основной поток.

2024-10-22 20:44 UTC, GusevaVarvara commented on tests/test_concurrent_futures.py
> +def test_cartesian_product_sum(numbers, expected_sum):
Я попробовала добавить вычисление суммы косинусов для декартового произведения и добавила тест на сравнение времени многопоточного и однопоточного подходов, но всё равно получилось, что однопоточный будет быстрее (по крайней мере на не очень больших числах), так как видимо эта функция тоже получилась не очень тяжёловесной.

2024-10-23 08:08 UTC, Krekep requested changes
Всё хорошо, но я не согласен с тестом на проверку числа активных потоков, его надо исправить

2024-10-23 08:08 UTC, Krekep commented on project/thread_pool.py
> +        """Инициализирует пул потоков с заданным числом потоков."""
Я что-то в каждой задаче у Вас пропустил отсутствие документации :(

В документации должны быть также отображены параметры, которые она принимает и значения, которые возвращает (если `None`, то можно не указывать). Также в [readme написано](https://github.com/GusevaVarvara/spbu-python-course/blob/e2432e08a5879336340b4b5c727494e83142ba4b/README.md?plain=1#L19), что документация должна быть на английском

2024-10-23 08:08 UTC, Krekep commented on tests/test_concurrent_futures.py
> +    print(f"Multi-threaded time: {multi_thread_time:.4f}s")
Тест обычно делает какую-то проверку. В данном случае Вы просто демонстрируете время работы, путём вывода в консоль. Это больше похоже на пример использования, чем на тест.

По поводу вычислительно-ёмкой  функции, к примеру:
```
def single_thread_func(a: list) -> int:
    res = 0
    for elem in a:
        res += math.sqrt(math.cos(elem) * math.sin(elem) + 1)
    return res
```

На 4 процессах и размере массива данных 4'000'000 у меня работает примерно в 6 (это много и не проверено, т.к. одноразовый запуск) раз быстрее, чем её однопоточный вариант. Также я для удобства преобразовал массив кортежей в одномерный массив

2024-10-23 08:08 UTC, Krekep commented on tests/test_thread_pool.py
> +    assert len(pool.threads) == 3
Всё верно, но при запуске теста явно видно, что Вы создаёте только один `ThreadPool`, поэтому использование `threading.active_count()` обосновано. Надо только помнить, что у Вас в дополнении к потокам пула, есть основной поток

2024-10-23 08:08 UTC, Krekep commented on tests/test_thread_pool.py
> +    assert len(pool.threads) == 3
`len(pool.threads) == 3` на самом деле проверяет, что Вы занесли в массив 3 элемента, а не то, что у Вас в данный момент времени действительно активны 3 потока в системе

2024-10-23 09:30 UTC, GusevaVarvara commented on tests/test_thread_pool.py
> +    assert len(pool.threads) == 3
Хорошо, поняла, исправила с использованием threading.active_count().

2024-10-23 09:32 UTC, GusevaVarvara commented on project/thread_pool.py
> +        """Инициализирует пул потоков с заданным числом потоков."""
Да, я не заметила это в readme, в следущий раз буду делать. В этой программе тоже исправила.

2024-10-23 10:21 UTC, GusevaVarvara commented on tests/test_concurrent_futures.py
> +    print(f"Multi-threaded time: {multi_thread_time:.4f}s")
Я исправила тест на сравнение работы двух подходов, теперь он сравнивает время работы, но я закоментировала эту проверку, так как у меня этот тест не проходит. Попробовала применить вашу фукцию, но у меня всё равно однопоточный процесс быстрее, возможно я что-то не так делаю.

2024-10-23 15:18 UTC, Krekep approved these changes
Есть замечания, но с учётом того, что в  целом всё хорошо и это третья попытка, то зачтено

2024-10-23 15:18 UTC, Krekep commented on project/concurrent_futures.py
> +def heavy_computation(pair):
Не хватает аннотаций типов

2024-10-23 15:18 UTC, Krekep commented on project/concurrent_futures.py
> +def cartesian_product_heavy_sum(numbers):
Не хватает аннотаций типов

2024-10-23 15:18 UTC, Krekep commented on tests/test_concurrent_futures.py
Можно добавить тест на сравнение быстродействия однопоточного варианта и многопроцессорного

2024-10-27 10:48 UTC, merged