Гусева. Task №5.
GusevaVarvara/spbu-python-course pull request #4
Opened 2024-10-28 20:38 UTC by GusevaVarvara

**Игра**

Реализация игры блэкджек (определение варианта игры: len(Гусева Варвара Алексеевна) = 6 + 7 + 10 = 23, 23 % 2 = 1, 1 + 1 = 2).

1. Реализованы три различных стратегии игры для ботов.
2. Добавлены методы, отображающие текущее состояние игры.
3. Каждая сущность в игре оформлена в виде отдельного класса.

В игре участвуют только боты, вывод информации о ходе игры осуществляется в консоль.
В папке examples добавлен пример работы игры с выводом состояния в каждом раунде.

Дополнительное задание:
Построена UML-диаграмма классов для наглядного представления структуры и взаимодействия классов игры.

2024-10-29 16:58 UTC, Krekep requested changes
В целом хорошо, но необходимы исправления

2024-10-29 16:58 UTC, Krekep commented on project/bot.py
> +        self.cards_on_hand: List[Card] = []
По факту у Вас две сущности --- бот и его рука, т.о. в текущем варианте класс `Bot` нарушает принцип единственной ответственности из SOLID.
Разделите класс на два

2024-10-29 16:58 UTC, Krekep commented on project/bot.py
> +            return "stand" if score >= 17 else "hit"
Магические константы (в данном случае действия) следует заменить на более читаемый и отслеживаемый подход (нет, не на магические числа)

2024-10-29 16:58 UTC, Krekep commented on project/dealer.py
> +        self.cards_on_hand: list[Card] = []
Same

2024-10-29 16:58 UTC, Krekep commented on project/dealer.py
> +        while self.calculate_score() < 17:
Почему 17? `according to the game rules` --- я не особо внимательно читал правила, поэтому если там действительно так написано, то скиньте пруф, а если нет, то, получается, у дилера тоже должна быть какая-то стратегия, которой он придерживается

2024-10-29 16:58 UTC, Krekep commented on project/bot.py
> +        if self.strategy == "Cautious":
Для реализации стратегий, кстати, можете посмотреть на [архитектурный паттерн "Стратегия"](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%82%D0%B5%D0%B3%D0%B8%D1%8F_(%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F))

2024-10-29 16:58 UTC, Krekep commented on project/bot.py
> +        if self.strategy == "Cautious":
Или даже не для самих стратегий, а для различных ботов, но тут на Ваше усмотрение

2024-10-29 16:58 UTC, Krekep commented on project/diagrams/uml_class_diagram.png.png
Лучше не мельчите, как минимум Card можно растянуть в ширину для читаемости
И мощность связей пишите не внутри класса, а у самих связей. Также указывайте мощность связи с обеих сторон (1 к 1, или 1 ко многим и т.д.)
По диаграмме видно, что у Вас все поля и методы являются публичными, что нарушает принцип инкапсуляции, исправьте

2024-10-29 16:58 UTC, Krekep commented on project/game.py
> +                        break
Бот проигрывает, но при этом продолжает участвовать в игре, что странно. Исправьте

2024-10-29 16:58 UTC, Krekep commented on tests/test_game.py
> +    assert score >= 17 or len(dealer.cards_on_hand) >= 2
Зачем здесь второе условие? По docstring тест проверяет, что у дилера счёт 17 или больше, а количество карт не важно

2024-10-29 18:40 UTC, Krekep commented
Замечание, о котором забыл --- у Вас не хватает ставок, добавьте их, и не забудьте про UML диаграмму.
И замените одну из стратегий, на более сложную, учитывающую историю ставок

2024-10-31 16:37 UTC, GusevaVarvara commented on project/bot.py
> +        self.cards_on_hand: List[Card] = []
Исправила, разделила на 2 класса

2024-10-31 16:37 UTC, GusevaVarvara commented on project/bot.py
> +            return "stand" if score >= 17 else "hit"
Убрала использование магических констант

2024-10-31 16:38 UTC, GusevaVarvara commented on project/dealer.py
> +        self.cards_on_hand: list[Card] = []
Исправила

2024-10-31 16:41 UTC, GusevaVarvara commented on project/dealer.py
> +        while self.calculate_score() < 17:
В задании была ссылка на страницу в Википедии, там в правилах написано: "Общее правило блек-джека состоит в том, что дилер обязан остановиться, как только наберёт 17 очков или выше, и обязан брать, пока не достигнет (даже если у всех не перебравших меньше очков)."

2024-10-31 16:43 UTC, GusevaVarvara commented on project/bot.py
> +        if self.strategy == "Cautious":
Я переделала с использованием подклассов со стратегиями от класса Bot

2024-10-31 16:45 UTC, GusevaVarvara commented on project/diagrams/uml_class_diagram.png.png
Переделала, учитывая изменения в программе

2024-10-31 16:58 UTC, GusevaVarvara commented on project/game.py
> +                        break
Бот проигрывает в одном из раундов, но продолжает участвовать в игре в следующих раундах. Я не знаю, как правильно в этой игре, но как я поняла, если сумма очков игрока превышает 21, то ставка игрока снимается в пользу казино (так написано в правилах), но в следущей раздаче игрок продолжает участвовать.

2024-10-31 16:59 UTC, GusevaVarvara commented on tests/test_game.py
> +    assert score >= 17 or len(dealer.cards_on_hand) >= 2
Убрала ненужное условие

2024-10-31 17:00 UTC, GusevaVarvara commented
Добавила ставки в игру, одна из стратегий ботов учитывает ставки

2024-11-01 17:43 UTC, Krekep requested changes
Необходимы исправления

2024-11-01 17:43 UTC, Krekep commented on project/bot.py
> +        balance (float): The bot's current balance.
Хранить деньги во float плохая практика, из-за проблем с округлением

2024-11-01 17:43 UTC, Krekep commented on project/dealer.py
> +        while score < 17 or score != 21:
Зачем здесь условие `score != 21`?

2024-11-01 17:43 UTC, Krekep commented on project/bot.py
> +        """Adjusts the bet based on previous round's result to manage risk."""
В описании этого бота сказано, что он меняет размер ставки в зависимости от результата предыдущего раунда.
Но в коде я вижу только условия, насчёт его текущего баланса и текущей ставки. В дополнении вопрос, почему в случае, когда баланс бота равен 50, он не изменит никак свою ставку относительно предыдущего раунда?

2024-11-01 17:43 UTC, Krekep commented on project/game.py
> +                if not dealer_blackjack:
Вы уже находитесь в ветке, где у дилера не блекджек

2024-11-01 17:43 UTC, Krekep commented on project/diagrams/uml_class_diagram.png.png
1. Карты содержатся в руке, рука принадлежит боту. Напрямую карты не принадлежат боту
2. Рисуйте стрелочки в одном стиле
3. Не хватает модификаторов видимости у методов в наследниках `Bot`
4. На диаграмме у Вас отмечены поля приватными, но в коде это никак не *подчёркнуто*
5. Также не все методы должны быть публичными (к примеру, `play_round`), это нарушает принцип инкапсуляции. Проверьте все методы на правильные модификаторы видимости (в код также не забудьте внести изменения)

2024-11-06 15:51 UTC, GusevaVarvara commented on project/bot.py
> +        balance (float): The bot's current balance.
Переделала с использованием Decimal, чтобы не было проблем с округлением.

2024-11-06 15:52 UTC, GusevaVarvara commented on project/dealer.py
> +        while score < 17 or score != 21:
Оно не нужно, я забыла убрать, когда переделывала цикл. Исправила

2024-11-06 15:55 UTC, GusevaVarvara commented on project/bot.py
> +        """Adjusts the bet based on previous round's result to manage risk."""
Я имела ввиду в зависимости от оставшегося после предыдущего раунда баланса, исправила описание и добавила изменение ставки при балансе равном 50.

2024-11-06 15:55 UTC, GusevaVarvara commented on project/game.py
> +                if not dealer_blackjack:
Да, убрала проверку

2024-11-06 16:02 UTC, GusevaVarvara commented on project/diagrams/uml_class_diagram.png.png
Исправила диаграмму и код. Правда в тестах я использую приватные методы для проверки их работы, наверное так не должно быть, но по логике мне кажется они должны быть приватными, поэтому я не стала делать их публичными, а тесты оставила как есть, чтобы понимать, что программа их проходит.

2024-11-07 09:46 UTC, Krekep commented on project/diagrams/uml_class_diagram.png.png
Использование в тестах приватных методов --- нормально (по крайней мере в Python)

2024-11-07 09:48 UTC, Krekep approved these changes
Зачтено

2024-11-07 09:48 UTC, Krekep commented on project/diagrams/uml_class_diagram.png.png
Почему карта и колода связаны отношением агрегации с дилером?

2024-11-08 13:03 UTC, merged